## Les bases de Pandas

In [8]:
import pandas as pd

CSV: Comma separated value
Dans les pays qui utilisent des versions non anglaises d'Excel, on peut avoir des fichiers avec un ; comme séparateur: adapter l'argument dep.

Autre delimiteurs:
tab
|
\#
 Pour normer les colonnes, on utilise names=['col1','col2','col3']
 pour lire que n lignes, on utilise nrows=10_000
 Ici n=10_000

In [12]:
cities_df =pd.read_csv('./population.csv',
                        sep=',',
                        encoding='cp1252')

In [16]:
df=(pd.read_csv('./population.csv',
                        sep=',',
                        encoding='cp1252', 
                        header=None,
                        names=['col1','col2', 'col3', 'col4','col5'],
                        usecols
                        dtype={'col1':str,'col3':int},
                        nrows=10)
               )

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1178972732.py, line 6)

In [18]:
cities_df1 = pd.read_csv('./population.csv', sep=',', encoding='latin-1')

In [20]:
cities_df1

            City / Urban area      Country  Population  Land area  Density
0              Tokyo/Yokohama        Japan    33200000       6993     4750
1              New York Metro          USA    17800000       8683     2050
2                   Sao Paulo       Brazil    17700000       1968     9000
3               Seoul/Incheon  South Korea    17500000       1049    16700
4                 Mexico City       Mexico    17400000       2072     8400
..                        ...          ...         ...        ...      ...
120                Copenhagen      Denmark     1525000        816     1850
121                  Brisbane    Australia     1508000       1603      950
122  Riverside/San Bernardino          USA     1507000       1136     1350
123                Cincinnati          USA     1503000       1740      850
124                     Accra        Ghana     1500000        453     3300

[125 rows x 5 columns]

In [22]:
type(cities_df)

pandas.core.frame.DataFrame

In [20]:
cities_df.shape

(125, 5)

In [22]:
# Nombre de ligne de data frame
cities_df.shape[0]

125

In [24]:
# Nombre de colonne de data frame
cities_df.shape[1]

5

In [26]:
assert cities_df.shape[0] >= 100, "le nombre de lignes est trop pétit (au moins 100 lignes néccessaires)"

## Information sur le data frame

In [29]:
cities_df.columns

Index(['City / Urban area', 'Country', 'Population', 'Land area', 'Density'], dtype='object')

In [33]:
cities_df.columns[-1]

'Density'

In [31]:
cities_df.dtypes

City / Urban area    object
Country              object
Population            int64
Land area             int64
Density               int64
dtype: object

In [35]:
cities_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City / Urban area  125 non-null    object
 1   Country            125 non-null    object
 2   Population         125 non-null    int64
 3   Land area          125 non-null    int64
 4   Density            125 non-null    int64
dtypes: int64(3), object(2)
memory usage: 5.0+ KB

In [37]:
cities_df.describe()

         Population    Land area       Density
count  1.250000e+02   125.000000    125.000000
mean   5.283232e+06  1399.624000   5403.600000
std    4.855835e+06  1340.851906   4935.181371
min    1.500000e+06   376.000000    700.000000
25%    2.100000e+06   583.000000   2250.000000
50%    3.502000e+06   816.000000   3800.000000
75%    6.000000e+06  1740.000000   7700.000000
max    3.320000e+07  8683.000000  29650.000000

In [39]:
cities_df.describe(include="all")

       City / Urban area Country    Population    Land area       Density
count                125     125  1.250000e+02   125.000000    125.000000
unique               125      52           NaN          NaN           NaN
top       Tokyo/Yokohama     USA           NaN          NaN           NaN
freq                   1      26           NaN          NaN           NaN
mean                 NaN     NaN  5.283232e+06  1399.624000   5403.600000
std                  NaN     NaN  4.855835e+06  1340.851906   4935.181371
min                  NaN     NaN  1.500000e+06   376.000000    700.000000
25%                  NaN     NaN  2.100000e+06   583.000000   2250.000000
50%                  NaN     NaN  3.502000e+06   816.000000   3800.000000
75%                  NaN     NaN  6.000000e+06  1740.000000   7700.000000
max                  NaN     NaN  3.320000e+07  8683.000000  29650.000000

## Statistiques de base

In [46]:
cities_df['Population']

0      33200000
1      17800000
2      17700000
3      17500000
4      17400000
         ...
120     1525000
121     1508000
122     1507000
123     1503000
124     1500000
Name: Population, Length: 125, dtype: int64

In [13]:
pd.read_clipboard()

ParserError: Expected 1 fields in line 5, saw 3. Error could possibly be due to quotes being ignored when a multi-char delimiter is used.

 df.drop_duplicates(): pour supprimer les doublons de lignes
 df.dropna(): pour supprimer les donner manquantes
 df.filter(): pour filtrer les lignes
 les fonctions peuvent travailler sur les lignes et sur les colonnes
 df.groupby('x'): pour faire des regrouppement
 df.fillna(): pour remplir les valeurs manquantes
 df.stack() : pour transformer les lignes en colonnes ou des colonnes en lignes
 df.concat([";"],axis=0) : pour concatener deux colonnes ou deux lignes

### Structure du dataframe

In [16]:
cities_df.shape

(125, 5)

In [18]:
# Nombre de ligne
cities_df.shape[0]

125

In [20]:
# Nombres de colonnes
cities_df.shape[1]

5

In [24]:
# nb_rows contient le nombre de ligne
nb_rows=cities_df.shape[0]

In [26]:
# liste des colonnes
cities_df.columns

Index(['City / Urban area', 'Country', 'Population', 'Land area', 'Density'], dtype='object')

### Informations sur dataframe

In [30]:
# Information de type
# pandas historique
# - objet (tout type de données, chaines caractères, nombres melangés, s'il y a une valeur manquante dans les données)
# il existe des types numeriques avec les données manquantes

cities_df.dtypes

City / Urban area    object
Country              object
Population            int64
Land area             int64
Density               int64
dtype: object

### Informations techniques

In [36]:
cities_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City / Urban area  125 non-null    object
 1   Country            125 non-null    object
 2   Population         125 non-null    int64
 3   Land area          125 non-null    int64
 4   Density            125 non-null    int64
dtypes: int64(3), object(2)
memory usage: 5.0+ KB

In [40]:
# description statistique
cities_df.describe()

         Population    Land area       Density
count  1.250000e+02   125.000000    125.000000
mean   5.283232e+06  1399.624000   5403.600000
std    4.855835e+06  1340.851906   4935.181371
min    1.500000e+06   376.000000    700.000000
25%    2.100000e+06   583.000000   2250.000000
50%    3.502000e+06   816.000000   3800.000000
75%    6.000000e+06  1740.000000   7700.000000
max    3.320000e+07  8683.000000  29650.000000

In [44]:
cities_df.describe(include='all', percentiles=[0.05,0.95])

       City / Urban area Country    Population    Land area       Density
count                125     125  1.250000e+02   125.000000    125.000000
unique               125      52           NaN          NaN           NaN
top       Tokyo/Yokohama     USA           NaN          NaN           NaN
freq                   1      26           NaN          NaN           NaN
mean                 NaN     NaN  5.283232e+06  1399.624000   5403.600000
std                  NaN     NaN  4.855835e+06  1340.851906   4935.181371
min                  NaN     NaN  1.500000e+06   376.000000    700.000000
5%                   NaN     NaN  1.540400e+06   453.000000    960.000000
50%                  NaN     NaN  3.502000e+06   816.000000   3800.000000
95%                  NaN     NaN  1.467000e+07  4184.800000  15030.000000
max                  NaN     NaN  3.320000e+07  8683.000000  29650.000000

In [46]:
cities_df.head(8)

  City / Urban area      Country  Population  Land area  Density
0    Tokyo/Yokohama        Japan    33200000       6993     4750
1    New York Metro          USA    17800000       8683     2050
2         Sao Paulo       Brazil    17700000       1968     9000
3     Seoul/Incheon  South Korea    17500000       1049    16700
4       Mexico City       Mexico    17400000       2072     8400
5  Osaka/Kobe/Kyoto        Japan    16425000       2564     6400
6            Manila  Philippines    14750000       1399    10550
7            Mumbai        India    14350000        484    29650

### Lecture de fichiers Excel

In [49]:
pd.read_excel('./population.xlsx')

,Unnamed: 0,City,Country,Population,Land area,Density
0,0,Tokyo/Yokohama,Japan,33200000,6993,4750
1,1,New York Metro,USA,17800000,8683,2050
2,2,Sao Paulo,Brazil,17700000,1968,9000
3,3,Seoul/Incheon,South Korea,17500000,1049,16700
4,4,Mexico City,Mexico,17400000,2072,8400
...,...,...,...,...,...,...
120,120,Copenhagen,Denmark,1525000,816,1850
121,121,Brisbane,Australia,1508000,1603,950
122,122,Riverside/San Bernardino,USA,1507000,1136,1350
123,123,Cincinnati,USA,1503000,1740,850
124,124,Accra,Ghana,1500000,453,3300

In [ ]:
# l'installation d'un moteur des fichiers Excel peut etre nécessaire
# ! permet d'exécuter une commande sur le système, ici l'installation d'un module
!pip install openpyxl

In [51]:
pd.read_excel('./population.xlsx').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  125 non-null    int64
 1   City        125 non-null    object
 2   Country     125 non-null    object
 3   Population  125 non-null    int64
 4   Land area   125 non-null    int64
 5   Density     125 non-null    int64
dtypes: int64(4), object(2)
memory usage: 6.0+ KB

In [55]:
# on peut aussi faire
ddf=pd.read_excel('./population.xlsx')
ddf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  125 non-null    int64
 1   City        125 non-null    object
 2   Country     125 non-null    object
 3   Population  125 non-null    int64
 4   Land area   125 non-null    int64
 5   Density     125 non-null    int64
dtypes: int64(4), object(2)
memory usage: 6.0+ KB

In [63]:
# Illustration sur la suppression d'une colonne
pd.read_excel('./population.xlsx').drop(columns=['Unnamed: 0 ']).info()

KeyError: "['Unnamed: 0 '] not found in axis"

###Lecture de données depuis une base de données SQL

In [29]:
import sqlite3
# Création de connexion vers la base de données
cnx=sqlite3.connect('population.sqlite')

In [31]:
pd.read_sql_query('SELECT*FROM population',cnx)

                         City      Country  Population  Land area  Density
0              Tokyo/Yokohama        Japan    33200000       6993     4750
1              New York Metro          USA    17800000       8683     2050
2                   Sao Paulo       Brazil    17700000       1968     9000
3               Seoul/Incheon  South Korea    17500000       1049    16700
4                 Mexico City       Mexico    17400000       2072     8400
..                        ...          ...         ...        ...      ...
120                Copenhagen      Denmark     1525000        816     1850
121                  Brisbane    Australia     1508000       1603      950
122  Riverside/San Bernardino          USA     1507000       1136     1350
123                Cincinnati          USA     1503000       1740      850
124                     Accra        Ghana     1500000        453     3300

[125 rows x 5 columns]

In [33]:
pd.read_sql_query('SELECT*FROM population',cnx).head(5)

             City      Country  Population  Land area  Density
0  Tokyo/Yokohama        Japan    33200000       6993     4750
1  New York Metro          USA    17800000       8683     2050
2       Sao Paulo       Brazil    17700000       1968     9000
3   Seoul/Incheon  South Korea    17500000       1049    16700
4     Mexico City       Mexico    17400000       2072     8400

In [35]:
pd.read_sql_query('SELECT*FROM population',cnx).head()

             City      Country  Population  Land area  Density
0  Tokyo/Yokohama        Japan    33200000       6993     4750
1  New York Metro          USA    17800000       8683     2050
2       Sao Paulo       Brazil    17700000       1968     9000
3   Seoul/Incheon  South Korea    17500000       1049    16700
4     Mexico City       Mexico    17400000       2072     8400

In [37]:
# Utilisation de clause where
# ici recuperation que de USA
pd.read_sql_query('SELECT*FROM population WHERE Country = "USA" ',cnx)

                        City Country  Population  Land area  Density
0             New York Metro     USA    17800000       8683     2050
1                Los Angeles     USA    11789000       4320     2750
2                    Chicago     USA     8308000       5498     1500
3               Philadelphia     USA     5149000       4661     1100
4                      Miami     USA     4919000       2891     1700
5          Dallas/Fort Worth     USA     4146000       3644     1150
6                     Boston     USA     4032000       4497      900
7                 Washington     USA     3934000       2996     1300
8                    Detroit     USA     3903000       3267     1200
9                    Houston     USA     3823000       3355     1150
10                   Atlanta     USA     3500000       5083      700
11     San Francisco/Oakland     USA     3229000       1365     2350
12              Phoenix/Mesa     USA     2907000       2069     1400
13                   Seattle     USA     2712000       2470     1100
14                 San Diego     USA     2674000       2026     1300
15      Minneapolis/St. Paul     USA     2389000       2316     1050
16                 St. Louis     USA     2078000       2147      950
17                 Baltimore     USA     2076000       1768     1150
18      Tampa/St. Petersburg     USA     2062000       2078     1000
19                    Denver     USA     1985000       1292     1550
20                 Cleveland     USA     1787000       1676     1050
21                Pittsburgh     USA     1753000       2208      800
22                  Portland     USA     1583000       1228     1300
23                  San Jose     USA     1538000        674     2300
24  Riverside/San Bernardino     USA     1507000       1136     1350
25                Cincinnati     USA     1503000       1740      850

In [39]:
pd.read_sql_query('SELECT*FROM population WHERE Country = "USA" ',cnx).shape

(26, 5)

### Les fonctions de traitement de données
- trouver les valeurs manquantes
- remplacer les valeurs manquantes
- trouver les valeurs abberantes
- filtrer des lignes
- calculer des nouvelles colonnes
- agreger/ regrouper des lignes
- croiser des tables(jointure)

### Valuers manquantes

In [89]:
cities_df.dropna()

            City / Urban area      Country  Population  Land area  Density
0              Tokyo/Yokohama        Japan    33200000       6993     4750
1              New York Metro          USA    17800000       8683     2050
2                   Sao Paulo       Brazil    17700000       1968     9000
3               Seoul/Incheon  South Korea    17500000       1049    16700
4                 Mexico City       Mexico    17400000       2072     8400
..                        ...          ...         ...        ...      ...
120                Copenhagen      Denmark     1525000        816     1850
121                  Brisbane    Australia     1508000       1603      950
122  Riverside/San Bernardino          USA     1507000       1136     1350
123                Cincinnati          USA     1503000       1740      850
124                     Accra        Ghana     1500000        453     3300

[125 rows x 5 columns]

In [91]:
cities_df.isna().head()

   City / Urban area  Country  Population  Land area  Density
0              False    False       False      False    False
1              False    False       False      False    False
2              False    False       False      False    False
3              False    False       False      False    False
4              False    False       False      False    False

In [93]:
# En phyton, True = 1, False = 0
cities_df.isna().sum()

City / Urban area    0
Country              0
Population           0
Land area            0
Density              0
dtype: int64

### Pour selectionner une colonne

In [41]:
cities_df['Country']

0            Japan
1              USA
2           Brazil
3      South Korea
4           Mexico
          ...
120        Denmark
121      Australia
122            USA
123            USA
124          Ghana
Name: Country, Length: 125, dtype: object

In [98]:
cities_df['Country'].isna()

0      False
1      False
2      False
3      False
4      False
       ...
120    False
121    False
122    False
123    False
124    False
Name: Country, Length: 125, dtype: bool

In [100]:
cities_df['Country'].isna().sum()

0

In [102]:
# Permet de filtrer (et voir) les lignes pour lesquelles on a des valeurs manquantes
#  Remarque : df[ ..........] permet de filtrer 
cities_df[cities_df['Country'].isna()]

Empty DataFrame
Columns: [City / Urban area, Country, Population, Land area, Density]
Index: []

In [104]:
cities_df['Population']>=15_000_000

0       True
1       True
2       True
3       True
4       True
       ...
120    False
121    False
122    False
123    False
124    False
Name: Population, Length: 125, dtype: bool

In [106]:
cities_df[cities_df['Population']>=15_000_000]

  City / Urban area      Country  Population  Land area  Density
0    Tokyo/Yokohama        Japan    33200000       6993     4750
1    New York Metro          USA    17800000       8683     2050
2         Sao Paulo       Brazil    17700000       1968     9000
3     Seoul/Incheon  South Korea    17500000       1049    16700
4       Mexico City       Mexico    17400000       2072     8400
5  Osaka/Kobe/Kyoto        Japan    16425000       2564     6400

In [108]:
# Mode avancé!!!
# On utilise le resultat de l'expression booléenne qui est une série (comme une autre, une colonne, etc.) pour faire un calcule 
#Les parenthèses permettent de bien isoler l'objet / Le resultat sur l'application de la fonction .sum()
(cities_df['Population']>=15_000_000).sum()

6

In [110]:
cities_15M_df = cities_df [cities_df['Population']>=15_000_000]

In [112]:
cities_15M_df

  City / Urban area      Country  Population  Land area  Density
0    Tokyo/Yokohama        Japan    33200000       6993     4750
1    New York Metro          USA    17800000       8683     2050
2         Sao Paulo       Brazil    17700000       1968     9000
3     Seoul/Incheon  South Korea    17500000       1049    16700
4       Mexico City       Mexico    17400000       2072     8400
5  Osaka/Kobe/Kyoto        Japan    16425000       2564     6400

### Quelques opp&rations d'énumeration

In [ ]:
## statistiques sur les colonnes

In [74]:
print(cities_df['Population'].mean())
print(cities_df['Population'].mode())
print(cities_df['Population'].())

5283232.0
0    4000000
Name: Population, dtype: int64

AttributeError: 'Series' object has no attribute 'sd'

In [47]:
cities_df['Country'].unique()

array(['Japan', 'USA', 'Brazil', 'South Korea', 'Mexico', 'Philippines',
       'India', 'Indonesia', 'Nigeria', 'Egypt', 'Argentina', 'Russia',
       'China', 'Pakistan', 'France', 'Turkey', 'UK', 'Germany', 'Iran',
       'Colombia', 'Peru', 'Thailand', 'South Africa', 'Taiwan', 'Iraq',
       'Chile', 'Congo', 'Vietnam', 'Spain', 'Malaysia', 'Canada',
       'Italy', 'Sudan', 'Saudi Arabia', 'Singapore', 'Greece',
       'Australia', 'Israel', 'Portugal', 'Puerto Rico', 'Poland',
       'Uzbekistan', 'Azerbaijan', 'UAE', 'Lebanon', 'Hungary',
       'Zimbabwe', 'Kuwait', 'Belgium', 'Austria', 'Denmark', 'Ghana'],
      dtype=object)

In [49]:
cities_df['Country'].nunique()

52

In [58]:
cities_df['Country'].value_counts()[:5]

Country
USA        26
Brazil      9
Germany     6
India       6
China       6
Name: count, dtype: int64

In [60]:
cities_df['Country'].value_counts()[0]

C:\Users\sodji\AppData\Local\Temp\ipykernel_27284\3630154804.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  cities_df['Country'].value_counts()[0]

26

In [62]:
cities_df['Country'].value_counts().index[0]

'USA'

In [64]:
## nom du deuxieme pays plus fréquents
cities_df['Country'].value_counts().index[1]

'Brazil'

In [68]:
cities_df['Country'].value_counts()[-5:]

Country
Thailand    1
Iraq        1
Chile       1
Vietnam     1
Ghana       1
Name: count, dtype: int64

### Filtrer les tableaaux

In [76]:
cities_df.query('Country=="USA" and Population >= 5000000')

   City / Urban area Country  Population  Land area  Density
1     New York Metro     USA    17800000       8683     2050
13       Los Angeles     USA    11789000       4320     2750
23           Chicago     USA     8308000       5498     1500
39      Philadelphia     USA     5149000       4661     1100

In [87]:
## Prenons l'habitude d' écrire les constantes en Majuscule

SEUIL_POPULATION=5_000_000

cities_df.query(f'Country=="USA" and Population >= {SEUIL_POPULATION}')

   City / Urban area Country  Population  Land area  Density
1     New York Metro     USA    17800000       8683     2050
13       Los Angeles     USA    11789000       4320     2750
23           Chicago     USA     8308000       5498     1500
39      Philadelphia     USA     5149000       4661     1100

In [93]:

PAYS_ANALYSE = 'France'
SEUIL_POPULATION = 5_000_000


cities_df.query(f'Country=="{PAYS_ANALYSE}" and Population >= {SEUIL_POPULATION}')

   City / Urban area Country  Population  Land area  Density
19             Paris  France     9645000       2723     3550

Créactin de nouvelles colonnes

In [96]:
9645000/2723

3542.049210429673

In [ ]:
## l'utilisation de l'affectation naturelle
cities_df['TrueDensity'] = cities_df['Population'] / cities_df[ 'Land area']

In [102]:
cities_df.head()

  City / Urban area      Country  Population  Land area  Density   TrueDensity
0    Tokyo/Yokohama        Japan    33200000       6993     4750   4747.604748
1    New York Metro          USA    17800000       8683     2050   2049.982725
2         Sao Paulo       Brazil    17700000       1968     9000   8993.902439
3     Seoul/Incheon  South Korea    17500000       1049    16700  16682.554814
4       Mexico City       Mexico    17400000       2072     8400   8397.683398

## Traitement des chaines de caractères

In [ ]:
## L' accesseur str permet de travailler sur les chaines de caractères

In [106]:
cities_df['Country'].str[0]

0      J
1      U
2      B
3      S
4      M
      ..
120    D
121    A
122    U
123    U
124    G
Name: Country, Length: 125, dtype: object

In [108]:
## deux premières caractères de la chaine
cities_df['Country'].str[:2]

0      Ja
1      US
2      Br
3      So
4      Me
       ..
120    De
121    Au
122    US
123    US
124    Gh
Name: Country, Length: 125, dtype: object

In [110]:
'DES MAJUSCULE'.lower()

'des majuscule'

In [112]:
cities_df['Country'].str.lower().head()

0          japan
1            usa
2         brazil
3    south korea
4         mexico
Name: Country, dtype: object

In [114]:
 ##Sans accesseur str, la fonction ne marche pas car il va falloir interpreter les elements de notre data comme 
## caractères avant d'y appliquer la fonction liée aux chaines de caractères
cities_df['Country'].lower().head()

AttributeError: 'Series' object has no attribute 'lower'

In [116]:
# Series 
cities_df[cities_df['Country'].str.lower().str.contains ('s')].head(3)

  City / Urban area      Country  Population  Land area  Density   TrueDensity
1    New York Metro          USA    17800000       8683     2050   2049.982725
3     Seoul/Incheon  South Korea    17500000       1049    16700  16682.554814
6            Manila  Philippines    14750000       1399    10550  10543.245175

In [122]:
cities_df[cities_df['Country'].str.lower().str.contains ('a')]['Country']. unique()

array(['Japan', 'USA', 'Brazil', 'South Korea', 'India', 'Indonesia',
       'Nigeria', 'Argentina', 'Russia', 'China', 'Pakistan', 'France',
       'Germany', 'Iran', 'Colombia', 'Thailand', 'South Africa',
       'Taiwan', 'Iraq', 'Vietnam', 'Spain', 'Malaysia', 'Canada',
       'Italy', 'Sudan', 'Saudi Arabia', 'Singapore', 'Australia',
       'Israel', 'Portugal', 'Poland', 'Uzbekistan', 'Azerbaijan', 'UAE',
       'Lebanon', 'Hungary', 'Zimbabwe', 'Kuwait', 'Austria', 'Denmark',
       'Ghana'], dtype=object)

In [124]:
cities_df.query('Country.str.lower().str.contains ("a")').head(3)

  City / Urban area Country  Population  Land area  Density  TrueDensity
0    Tokyo/Yokohama   Japan    33200000       6993     4750  4747.604748
1    New York Metro     USA    17800000       8683     2050  2049.982725
2         Sao Paulo  Brazil    17700000       1968     9000  8993.902439

In [126]:
transcoder = { 'USA' : 'United States of America', 'UK' : 'United Kingdom'}

In [130]:
cities_df.replace({'Country': transcoder})['Country'].unique()

array(['Japan', 'United States of America', 'Brazil', 'South Korea',
       'Mexico', 'Philippines', 'India', 'Indonesia', 'Nigeria', 'Egypt',
       'Argentina', 'Russia', 'China', 'Pakistan', 'France', 'Turkey',
       'United Kingdom', 'Germany', 'Iran', 'Colombia', 'Peru',
       'Thailand', 'South Africa', 'Taiwan', 'Iraq', 'Chile', 'Congo',
       'Vietnam', 'Spain', 'Malaysia', 'Canada', 'Italy', 'Sudan',
       'Saudi Arabia', 'Singapore', 'Greece', 'Australia', 'Israel',
       'Portugal', 'Puerto Rico', 'Poland', 'Uzbekistan', 'Azerbaijan',
       'UAE', 'Lebanon', 'Hungary', 'Zimbabwe', 'Kuwait', 'Belgium',
       'Austria', 'Denmark', 'Ghana'], dtype=object)


## Regroupement de lignes/ agrégats/ group by

In [132]:
cities_df.groupby(['Country'])

In [136]:
cities_df.groupby(['Country'])['Population'].mean().head(3)

Country
Argentina    11200000.0
Australia     2724000.0
Austria       1550000.0
Name: Population, dtype: float64

L'astuce de la parenthèse (parentheis trich)

In [147]:
( cities_df
 .groupby(['Country'])
  .agg({'Population': ['mean', 'max', 'sum'], 'Land area':['mean', 'max', 'sum']})
 .head(3)
)

           Population                     Land area
                 mean       max       sum      mean   max   sum
Country
Argentina  11200000.0  11200000  11200000    2266.0  2266  2266
Australia   2724000.0   3502000   8172000    1790.0  2080  5370
Austria     1550000.0   1550000   1550000     453.0   453   453

### Visualisation